flowchart TB
    User[Usuario]
    Blazor[Blazor Frontend]
    Api[ASP.NET Core API]
    Auth[JWT + Policies]
    App[Application Layer]
    Domain[Domain Model]
    Ef[EF Core]
    Sql[(SQL Server)]
    Outbox[Outbox Worker]
    Docs[OpenAPI Docs]

    User --> Blazor
    Blazor --> Api
    Api --> Auth
    Api --> App
    App --> Domain
    App --> Ef
    Ef --> Sql
    App --> Outbox
    Outbox --> Sql
    Api --> Docs
