flowchart TB
    subgraph Monolito_Modular[Monolito modular]
      A[API única]
      B[Catalog Module]
      C[Orders Module]
      D[(Base de datos compartida)]
      A --> B
      A --> C
      B --> D
      C --> D
    end

    subgraph Microservicios[Microservicios]
      E[Catalog API] --> F[(Catalog DB)]
      G[Orders API] --> H[(Orders DB)]
      G -. HTTP/Event .-> E
    end
