CREATE SCHEMA academy;
GO

CREATE TABLE academy.Students
(
    Id UNIQUEIDENTIFIER NOT NULL PRIMARY KEY,
    Email NVARCHAR(320) NOT NULL UNIQUE,
    FullName NVARCHAR(200) NOT NULL,
    IsActive BIT NOT NULL,
    CreatedAt DATETIMEOFFSET NOT NULL
);

CREATE TABLE academy.Courses
(
    Id UNIQUEIDENTIFIER NOT NULL PRIMARY KEY,
    Code NVARCHAR(30) NOT NULL UNIQUE,
    Name NVARCHAR(200) NOT NULL,
    Status NVARCHAR(30) NOT NULL,
    CreatedAt DATETIMEOFFSET NOT NULL,
    CONSTRAINT CK_Courses_Status CHECK (Status IN ('Draft', 'Published'))
);

CREATE TABLE academy.Enrollments
(
    Id UNIQUEIDENTIFIER NOT NULL PRIMARY KEY,
    StudentId UNIQUEIDENTIFIER NOT NULL,
    CourseId UNIQUEIDENTIFIER NOT NULL,
    CreatedAt DATETIMEOFFSET NOT NULL,
    CONSTRAINT FK_Enrollments_Students FOREIGN KEY (StudentId) REFERENCES academy.Students(Id),
    CONSTRAINT FK_Enrollments_Courses FOREIGN KEY (CourseId) REFERENCES academy.Courses(Id),
    CONSTRAINT UQ_Enrollments UNIQUE (StudentId, CourseId)
);

CREATE TABLE academy.OutboxMessages
(
    Id UNIQUEIDENTIFIER NOT NULL PRIMARY KEY,
    Type NVARCHAR(250) NOT NULL,
    Payload NVARCHAR(MAX) NOT NULL,
    OccurredAt DATETIMEOFFSET NOT NULL,
    ProcessedAt DATETIMEOFFSET NULL,
    Attempts INT NOT NULL DEFAULT 0,
    Error NVARCHAR(MAX) NULL
);
