@baseUrl = http://localhost:5000

GET {{baseUrl}}/health

###
GET {{baseUrl}}/products

###
POST {{baseUrl}}/products
Content-Type: application/json

{
  "name": "Keyboard",
  "basePrice": 80,
  "stock": 25,
  "isPremium": true
}

###
GET {{baseUrl}}/products/11111111-1111-1111-1111-111111111111/price
