CREATE SCHEMA courses;
GO

CREATE SCHEMA students;
GO

CREATE SCHEMA enrollments;
GO

CREATE TABLE courses.Courses
(
    Id UNIQUEIDENTIFIER NOT NULL PRIMARY KEY,
    Code NVARCHAR(30) NOT NULL UNIQUE,
    Name NVARCHAR(200) NOT NULL
);

CREATE TABLE students.Students
(
    Id UNIQUEIDENTIFIER NOT NULL PRIMARY KEY,
    Email NVARCHAR(320) NOT NULL UNIQUE,
    FullName NVARCHAR(200) NOT NULL
);

CREATE TABLE enrollments.Enrollments
(
    Id UNIQUEIDENTIFIER NOT NULL PRIMARY KEY,
    CourseId UNIQUEIDENTIFIER NOT NULL,
    StudentId UNIQUEIDENTIFIER NOT NULL,
    CreatedAt DATETIMEOFFSET NOT NULL,
    CONSTRAINT UQ_Enrollment UNIQUE (CourseId, StudentId)
);
