@baseUrl = http://localhost:5000

POST {{baseUrl}}/sql/products
Content-Type: application/json

{
  "name": "Architecture Notebook",
  "price": 15,
  "category": "Books"
}

###
GET {{baseUrl}}/sql/products

###
POST {{baseUrl}}/nosql/profiles
Content-Type: application/json

{
  "id": "",
  "email": "student@example.com",
  "displayName": "Student",
  "preferences": {
    "theme": "dark",
    "language": "es"
  },
  "tags": ["dotnet", "architecture"]
}
